# fly.toml app configuration file generated for pv-thermal-inspection-gi on 2026-03-02T00:47:45+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pv-thermal-inspection-gi'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile.fly'

[env]
  CORS_ALLOW_ORIGINS = '*'
  FAULT_MODEL_PATH = '/app/backend/models/best.pt'
  FAULT_TYPE_MODEL_PATH = '/app/backend/models/best_8_class.pt'
  PRELOAD_MODEL = '0'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'requests'
    hard_limit = 40
    soft_limit = 20

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
